// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Nude.Data.Infrastructure.Contexts;

#nullable disable

namespace Nude.Bot.Tg.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20230423094140_nude-db")]
    partial class nudedb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nude.API.Models.Media.TelegramMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_key");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_id");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer")
                        .HasColumnName("media_type");

                    b.HasKey("Id")
                        .HasName("pk_medias");

                    b.ToTable("medias", (string)null);
                });

            modelBuilder.Entity("Nude.API.Models.Messages.Details.MessageDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("discriminator");

                    b.HasKey("Id")
                        .HasName("pk_message_details");

                    b.ToTable("message_details", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("MessageDetails");
                });

            modelBuilder.Entity("Nude.API.Models.Messages.UserMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<int>("DetailsId")
                        .HasColumnType("integer")
                        .HasColumnName("details_id");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("DetailsId")
                        .IsUnique()
                        .HasDatabaseName("ix_messages_details_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_messages_owner_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Nude.API.Models.Users.TelegramUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Nude.API.Models.Messages.Details.ContentTicketDetails", b =>
                {
                    b.HasBaseType("Nude.API.Models.Messages.Details.MessageDetails");

                    b.Property<string>("ContentKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_key");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    b.HasDiscriminator().HasValue("ContentTicketDetails");
                });

            modelBuilder.Entity("Nude.API.Models.Messages.Details.MediaGroupDetails", b =>
                {
                    b.HasBaseType("Nude.API.Models.Messages.Details.MessageDetails");

                    b.Property<int>("CurrentMedia")
                        .HasColumnType("integer")
                        .HasColumnName("current_media");

                    b.Property<string>("MediaGroupId")
                        .HasColumnType("text")
                        .HasColumnName("media_group_id");

                    b.Property<int>("TotalMedia")
                        .HasColumnType("integer")
                        .HasColumnName("total_media");

                    b.HasDiscriminator().HasValue("MediaGroupDetails");
                });

            modelBuilder.Entity("Nude.API.Models.Messages.UserMessage", b =>
                {
                    b.HasOne("Nude.API.Models.Messages.Details.MessageDetails", "Details")
                        .WithOne("Message")
                        .HasForeignKey("Nude.API.Models.Messages.UserMessage", "DetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_message_details_details_id");

                    b.HasOne("Nude.API.Models.Users.TelegramUser", "Owner")
                        .WithMany("Messages")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_owner_id");

                    b.Navigation("Details");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Nude.API.Models.Messages.Details.MessageDetails", b =>
                {
                    b.Navigation("Message")
                        .IsRequired();
                });

            modelBuilder.Entity("Nude.API.Models.Users.TelegramUser", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
